on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Clean
      run: dotnet clean --configuration Release && dotnet nuget locals all --clear
    - name: Build
      run: dotnet build --configuration Release --no-restore
