on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build
      run: dotnet build --configuration Release
    - name: Build for Windows
      run: dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true
    - name: Show contents of the current working directory
      run: ls -R
    - name: Upload artifact - Windows
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Scraper.exe
        path: WebScraperDemo/bin/Release/netcoreapp3.1/win-x64/publish/Scraper.exe
